/* Final Project
Michael McLaughlin
CIT 178 */

USE FinalProject;

GO

ALTER TABLE Game WITH CHECK
ADD CONSTRAINT FK_Console FOREIGN KEY(ConsoleID) REFERENCES Console(ConsoleID)
ON UPDATE CASCADE;

GO

ALTER TABLE Game WITH CHECK
ADD CONSTRAINT FK_Publisher FOREIGN KEY(PublisherID) REFERENCES Publisher(PublisherID)
ON UPDATE CASCADE;

GO

ALTER TABLE Game WITH CHECK
ADD CONSTRAINT FK_Developer FOREIGN KEY(DeveloperID) REFERENCES Developer(DeveloperID)
ON UPDATE CASCADE;

GO

ALTER TABLE Game WITH CHECK
ADD CONSTRAINT FK_MediaType FOREIGN KEY(MediaTypeID) REFERENCES MediaType(MediaTypeID)
ON UPDATE CASCADE;

GO

ALTER TABLE Game WITH CHECK
ADD CONSTRAINT FK_Genre FOREIGN KEY(GenreID) REFERENCES Genre(GenreID)
ON UPDATE CASCADE;